name: "Dumbster fire"

on:
  push:
    branches:
      - master
      - 'releases/**'

jobs:
  release:
    name: "Release the kraken"
    runs-on: ubuntu-latest

    steps:
      - run: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash | export NVM_DIR="$HOME/.nvm"
      - run: nvm install 0.6.9
      - run: yarn && yarn build
      - run: zip -r batarang.zip .
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.zip